---
title: "ModelComparisonOptions_MaleOnly"
author: "Ellie Weise"
date: "2026-01-20"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Elastic Net (current option)

```{r,message=F,warning=FALSE}
#load libraries
library(tidyverse)
library(glmnet)
library(MASS)
library(wesanderson)
library(ggforce)
###run clock with best CpG sites
CpGlist_all <- read.csv(file = "Output/CpGList_LengthAge_MAEBestModels_MaleOnly.csv")

##load data
# if doing clock from scratch
load("MethylKitInput/allCpGs_MinimalMissing.rda")
sexdata <- read.csv("Input/MethylWild_Sex_AgeData.csv")

```

### Preparing data for elastic net
```{r}
## Data prep ####
#set.seed(234578)
set.seed(2345)
# subset to age 4-19 wild data
# get rid of sparse data issue for now as well
sexdata <- sexdata %>% 
  filter(DataType == "Wild" & ObsSex == 1 & Age < 21)

#running a glmnet with all selected sites
#CpGlist_all <- CpGlist_all %>% filter(ModelType == "Age")
bestCpGs <- allCpGs1[,which(colnames(allCpGs1) %in% CpGlist_all$CpGlist_best)]

#remove CpGs with NAs for the model
nas <- colSums(is.na(bestCpGs))
#bestCpGs <- bestCpGs[,which(nas < 1)]
bestCpGs <- cbind(indivname=allCpGs1$indivname,bestCpGs)

#log age data
sexdata <- sexdata %>% 
  mutate(LogAge = log(Age),LogLen = log(Length))
```


### Separating into Training and Testing Data Sets 
```{r}
#randomly select individuals for testing
testpick <- sexdata %>% 
  group_by(Age) %>% 
  slice_sample(n = 1)

#sort other individuals into training data
trainpick <- sexdata[which(!(sexdata$indivname %in% testpick$indivname)),]

#select CpG sites for each group
testdat <- bestCpGs[which(bestCpGs$indivname %in% testpick$indivname),]
testdat <- left_join(testpick,testdat,by = "indivname")

traindat <- bestCpGs[which(!(bestCpGs$indivname %in% testpick$indivname)),]
traindat <- left_join(trainpick,traindat,by = "indivname")
```

### Run Elastic Net Model on Training Set and Predict Test Set
```{r,warning=F}
## Full Data Model ####
#select data and run glmnet to select sites
y <- traindat$LogAge

#running a glmnet with all selected sites
bestCpG_train <- as.matrix(traindat[,which(colnames(traindat) %in% CpGlist_all$CpGlist_best)])

nas <- colSums(is.na(bestCpG_train))
bestCpG_train <- bestCpG_train[,which(nas < 1)]

model1 <- cv.glmnet(bestCpG_train,y,family = "gaussian",alpha = 0.05,nfolds = 20)
coef.allCpG <- as.matrix(coef(model1,s = "lambda.min"))

bestCpGnames <- names(coef.allCpG[which(coef.allCpG > 0),])

#predict testdat
ytest <- testdat$LogAge
xtest <- as.matrix(testdat[,which(colnames(testdat) %in% CpGlist_all$CpGlist_best)])
nas <- colSums(is.na(bestCpG_train))
xtest <- xtest[,which(nas < 1)]

#predict and correlate train data
pred_logage <- predict(model1,newx = bestCpG_train,type = "response",s = model1$lambda.1se)
colnames(pred_logage) <- "Epi_LogAge"
train_cor <- cor.test(y,pred_logage)
plot(y,pred_logage,col = traindat$ObsSex)

plot(model1, xvar = "dev", label = TRUE)

#predict and correlate test data
pred_logage_test <- predict(model1,newx = xtest,type = "response",s = model1$lambda.1se)
colnames(pred_logage_test) <- "Epi_LogAge"
test_cor <- cor.test(ytest,pred_logage_test)
plot(ytest,pred_logage_test,col = testdat$ObsSex)

#uncertainty for train and test
train_MAE <- median(abs(exp(y) - exp(pred_logage[ ,1])))
test_MAE <- median(abs(exp(ytest) - exp(pred_logage_test[ ,1])))
print(c(train_MAE,test_MAE))

# plot prediction
#clock correlation plot
train_res <- data.frame(indivname=traindat$indivname,
                        ObsSex=traindat$ObsSex,
                        Length=traindat$Length,
                        LogAge=y,
                        Epi_LogAge=pred_logage,
                        type="Train",
                        sampletype=traindat$DataType)
test_res <- data.frame(indivname=testdat$indivname,
                       ObsSex=testdat$ObsSex,
                       Length=testdat$Length,
                       LogAge=ytest,
                       Epi_LogAge=pred_logage_test,
                       type="Test",
                       sampletype=testdat$DataType)
res_comb_all <- rbind(train_res,test_res)
res_comb_all <- res_comb_all %>% mutate(Age=exp(LogAge),EpiAge=exp(Epi_LogAge)) %>% 
  dplyr::select(-LogAge,-Epi_LogAge,-sampletype)
res_comb_all$SampleSet <- "Male-Only"
res_comb_all$ModelType <- "Elastic Net"
ggplot(res_comb_all,aes(x = Age,y = EpiAge,color=as.character(ObsSex),shape = type))+
  geom_point(size = 3.5)+
  geom_jitter(height = 0,width = 0.1)+
  ylim(0, 30) + xlim(0, 30) +
  geom_abline(slope = 1,intercept = 0) +
  xlab("Otolith Age (years)") +
  ylab("Molecular clock Age (years)") +
  ggtitle("Correlation Between Otolith and Molecular Clock Age") +
  scale_color_manual(values = c(wes_palette("IsleofDogs1")[1]))+
  theme_classic(base_size = 18) + 
  theme(legend.position = "none")
```

### GAM testing

```{r}
# check for multi-colinearity
library(mRMRe)
library(mgcv)
library(stats)

testdf <- left_join(sexdata,bestCpGs)
CpGs <- testdf %>% 
  dplyr::select(starts_with("NC"))

Ages <- testdf$Age
indivnames <- testdf$indivname

## run a model with all CpGs and remove zerod out factors
gam_reduce <- gam(Age ~ #s(NC_047151.1.10083, bs="ts") +
s(NC_047151.1.10551, bs="ts") +
#s(NC_047151.1.11792, bs="ts") +
#s(NC_047151.1.1363, bs="ts") +
s(NC_047151.1.15812, bs="ts") +
#s(NC_047151.1.380, bs="ts") +
s(NC_047151.1.387, bs="ts") +
s(NC_047151.1.4382, bs="ts") +
#s(NC_047151.1.5724, bs="ts") +
s(NC_047152.1.2310, bs="ts") +
#s(NC_047152.1.3646, bs="ts") +
s(NC_047152.1.5986, bs="ts") +
s(NC_047152.1.7322, bs="ts") +
#s(NC_047153.1.32663007, bs="ts") +
#s(NC_047153.1.32663014, bs="ts") +
#s(NC_047153.1.32664011, bs="ts") +
#s(NC_047153.1.32666784, bs="ts") +
#s(NC_047153.1.32669085, bs="ts") +
#s(NC_047153.1.32672419, bs="ts") +
#s(NC_047155.1.30745806, bs="ts") +
#s(NC_047155.1.30749276, bs="ts") +
#s(NC_047155.1.30749968, bs="ts") +
#s(NC_047155.1.30750957, bs="ts") +
#s(NC_047155.1.30751963, bs="ts") +
s(NC_047159.1.29159369, bs="ts") +
#s(NC_047159.1.29166769, bs="ts") +
#s(NC_047159.1.29169109, bs="ts") +
#s(NC_047159.1.29170064, bs="ts") +
s(NC_047161.1.22201614, bs="ts") +
#s(NC_047162.1.17156, bs="ts") +
#s(NC_047165.1.15411799, bs="ts") +
#s(NC_047165.1.15412581, bs="ts") +
s(NC_047168.1.6544, bs="ts") +
#s(NC_047169.1.16885311, bs="ts") +
#s(NC_047172.1.26300329, bs="ts") +
#s(NC_047172.1.26301670, bs="ts") +
#s(NC_047172.1.26302005, bs="ts") +
s(NC_047172.1.26302372, bs="ts") +
#s(NC_047172.1.26303009, bs="ts") +
s(NC_047172.1.26307026, bs="ts") +
#s(NC_047172.1.26308364, bs="ts") +
s(NC_047172.1.26309369, bs="ts"),
#s(NC_047172.1.26311408, bs="ts") +
#s(NC_047174.1.21435055, bs="ts"),
select = T,data = testdf,method = "REML")

summary(gam_reduce)

# linearize factors with an edf of 1
gam_model3 <- gam(Age ~ #NC_047151.1.10551 +
#NC_047151.1.15812 +
s(NC_047151.1.387, bs="ts") +
#NC_047151.1.4382 +
NC_047152.1.2310 +
NC_047152.1.5986 +
NC_047152.1.7322 +
NC_047159.1.29159369 +
NC_047161.1.22201614 +
NC_047168.1.6544 +
#NC_047172.1.26302372 +
#NC_047172.1.26307026 +
s(NC_047172.1.26309369, bs="ts"),
select = T,data = testdf,method = "REML")

summary(gam_model3)
 
concur <- concurvity(b=gam_model3,full = F)

range(concur[["estimate"]])
hist(concur[["estimate"]],breaks = 20)

which(concur[["estimate"]] > 0.9, arr.ind = TRUE)

# try predictions just to see
predictions2 = predict(gam_model3,type = 'response',se = TRUE)

predictions2[["numb"]] <- names(predictions2$fit)

df_preds = data.frame(indivname=testdf$indivname,Age=testdf$Age)
df_preds <- df_preds[as.numeric(predictions2[["numb"]]),] %>% 
  mutate(fit = predictions2[["fit"]],
         se.fit = predictions2[["se.fit"]]) %>% 
  mutate(lower = fit - 1.96 * se.fit,
         upper = fit + 1.96 * se.fit) %>% 
  left_join(sexdata)

# save data in same
gam_res <- data.frame(df_preds,type="Test") %>% 
  dplyr::rename(EpiAge=fit)

gam_res$SampleSet <- "Male-Only"
gam_res$ModelType <- "GAM"

# calculate MAE
median(abs(df_preds$Age - df_preds$fit))
cor.test(df_preds$Age, df_preds$fit)
ggplot(aes(x = Age, y = fit,color = as.factor(ObsSex)), data = df_preds) +
  geom_point(size = 2)+
  ylim(0, 30) + xlim(0, 30) +
  geom_abline(slope = 1,intercept = 0)+
  xlab("Otolith Age (years)") +
  ylab("Molecular clock Age (years)") +
  ggtitle("GAM Predictions Between Otolith and Molecular Clock Age") +
  scale_color_manual(values = c(wes_palette("IsleofDogs1")[1],wes_palette("IsleofDogs1")[3]))+
  theme_classic(base_size = 18) + 
  theme_minimal()


```


```{r}
# save predictions for figures
preds_comb <- full_join(res_comb_all,gam_res)
write.csv(preds_comb,file = "PredsMaleOnly_BestModels.csv",quote = F,row.names = F, append = F)
```








